const panaderia ={
    nombre: "Productos Mayoristas",
    tipos:[
        {   nombre: "Pan de Masa Madre",
            productos:[
                {nombre: "Baguette Blanca",
                peso: "890gr",
                precio: 1000,
                },
                {nombre: "Foccacia de Tomate y Cebolla",
                peso: "890gr",
                precio: 1000,
                },
                {nombre: "Pan Aleman",
                peso: "890gr",
                precio: 1000,
                },
                {nombre: "Pan Semi Integral con Chia",
                peso: "890gr",
                precio: 1000,
                },
                {nombre: "Pan de Centeno",
                peso: "890gr",
                precio: 1000,
                },
                {nombre: "Pan de Campiña",
                peso: "890gr",
                precio: 1000,
                },
                {nombre: "Pan de Zanahoria",
                peso: "890gr",
                precio: 1000,
                },
                {nombre: "Prepizza de Filetto",
                peso: "890gr",
                precio: 1000,
                },
            ],
        },
        {
            nombre: "Tortas",
            productos:[
                {nombre: "Selva Negra",
                peso: "890gr",
                precio: 1000,
                },
                {nombre: "Bombon",
                peso: "890gr",
                precio: 1000,
                },
                {nombre: "Frutilla con crema",
                peso: "890gr",
                precio: 1000,
                },
                {nombre: "Moka",
                peso: "890gr",
                precio: 1000,
                },
                {nombre: "Cheesecake",
                peso: "890gr",
                precio: 1000,
                },
                {nombre: "Tiramisu",
                peso: "890gr",
                precio: 1000,
                },
                {nombre: "Carrot cake",
                peso: "890gr",
                precio: 1000,
                },
            ],
        },
        {
            nombre: "Tartas",
            productos:[
                {nombre: "Strudel de Manzana",
                peso: "890gr",
                precio: 1000,
                },
                {nombre: "Streusel de Peras",
                peso: "890gr",
                precio: 1000,
                },
                {nombre: "Ricota y Limon",
                peso: "890gr",
                precio: 1000,
                },
                {nombre: "Linzer de Moras y Arandanos",
                peso: "890gr",
                precio: 1000,
                },
            ],    
        },
        {
            nombre: "Panes Envasados",
            productos:[
                {nombre: "Ciabatta",
                peso: "890gr",
                precio: 1000,
                },
                {nombre: "Multicereal",
                peso: "890gr",
                precio: 1000,
                },
                {nombre: "Brioche de Molde",
                peso: "890gr",
                precio: 1000,
                },
                {nombre: "Bagel",
                peso: "890gr",
                precio: 1000,
                },
                {nombre: "Pan de Papa blanco",
                peso: "890gr",
                precio: 1000,
                },
                {nombre: "Pan de Campo",
                peso: "890gr",
                precio: 1000,
                },
                {nombre: "Zepelin",
                peso: "890gr",
                precio: 1000,
                },
            ],    
        },
        {
            nombre: "Especialidades",
            productos:[
                {nombre: "Alfajor de Maicena",
                peso: "890gr",
                precio: 1000,
                },
                {nombre: "Alfajor de Nuez",
                peso: "890gr",
                precio: 1000,
                },
                {nombre: "Alfajor Marplatense",
                peso: "890gr",
                precio: 1000,
                },
                {nombre: "Individual Brownie",
                peso: "890gr",
                precio: 1000,
                },
                {nombre: "Individual Frolla",
                peso: "890gr",
                precio: 1000,
                },
                {nombre: "Individual Limon",
                peso: "890gr",
                precio: 1000,
                },
                {nombre: "Individual Coco con DDL",
                peso: "890gr",
                precio: 1000,
                },
                {nombre: "Cookie de Avena",
                peso: "890gr",
                precio: 1000,
                },
                {nombre: "Cookie de Chocolate",
                peso: "890gr",
                precio: 1000,
                },
                {nombre: "Cookie de Manteca de Mani",
                peso: "890gr",
                precio: 1000,
                },
            ],    
        },
    ],
};
export default panaderia